# Evaluating Differences Between Observers and the impact on Detection of Noctural ATV surveys
## Auriel M.V. Fournier
## March 31, 2015

Goal - To determine if repeat nocturnal ATV surveys for rails detect the same individuals and how detection varies as a result of distance from the transect line. 

Observer bias and variability is one of the large causes of worry and violations of many assumptions when surveying wildlife populations, for an unvetted survey method like nocturnal ATV surveys this is especially true. 

I propose using the marked point patterns from repeated surveys on the same nights to assess differences in observers and to determine if two surveys on the same night observer comparable numbers of birds. 

## Introduction

Rails are very difficult to detect, which makes surveying for them, and assessing the success of those surveys, very challenging. Rails are difficult to detect because they don't vocalize regularly in the fall, and do not respond to vocalizations, and their behavior has them dense in vegetation most of the time. They are also reluctant to flush out of the vegetation until you are very close to them. This is one of the reasons they are the least studied group of birds in North America and why there are no standard survey methods for them outside of the breeding season (Conway 2012). 

In 2013 and 2014 my project did double surveys each night, in which a wetland impoundment was surveyed two times, by two different people, in a short period of time (3 hours). Since rails are active during the day other then responding to our presence in the wetland (for which I have telemetry data to support they only move 3-10 meters) we are assuming that they are sleeping or still the rest of the night. As a result we hope that these two surveys are surveying the same birds in roughly the same locations. I propose using point pattern analysis to examine the differences in marked point patterns from 2013 and 2014. I will look at distance from the line and how it impacts detection along with differences in the patterns of points between the two observers. 

## Methods

I have a marked point patterns of observations of rails on 13 different public properties in 45 different wetland units across 6 months of surveys (3 months in each year). I will summarize the differences in pattern at the wetland level, as that is the unit of interest to my project as a whole and is the unit at which we consider the survey to be completed. 

Across that time period we had four different observers (four in 2013 and two returning in 2014). 

```{r}
library(ggplot2)
library(rgdal)
library(gridExtra)
setwd("C:/Users/avanderlaar/Documents/GitHub/data")
dat <- read.csv("all_birds.csv")
dat <- na.omit(dat)

utm <- as.data.frame(project(cbind(dat$long, dat$lat), "+proj=utm +zone=15 ellps=WGS84"))
colnames(utm) <- c("utm_w","utm_n")

dat <- cbind(dat, utm)
dat4 <- dat[dat$year==2014,]


jdate4 <- unique(dat4$jdate)


list4 <- list()


## so this takes each day adn makes a list with each unique date being a level in the lsit
# removes days in which only one observer saw birds
for(i in 1:length(jdate4)){
  dat <- dat4[dat4$jdate==jdate4[i],]
  if (length(unique(dat$obs))>1){
  list4[[i]] <- dat}
}



## this pairs up eahc point with the nearest point by the other observer and measures the difference

dist4 <- list()
newdf <- list()

for (i in c(1:14,16:21,24:40)) {
  df <- as.data.frame(list4[[i]])
  if (nrow(df)>1){
  a <- df[df$obs=="N",]
  b <- df[df$obs=="A",]
            for(j in 1:nrow(a)){
            c <- b[which.min(sqrt(abs(a[j,"utm_n"]-b[,"utm_n"])^2 + abs(a[j,"utm_w"]-b[,"utm_w"])^2)),]
            d <- a[j,]
            c$dist <- min(sqrt(abs(a[j,"utm_n"]-b[,"utm_n"])^2 + abs(a[j,"utm_w"]-b[,"utm_w"])^2))
            dist4[[j]] <- cbind(c,d)
      }
  newdf[[i]] <- do.call(rbind, dist4)
}}


dist <- do.call(rbind, newdf)


ggplot(data=dist[dist$canwr=="nvca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("nv")
ggplot(data=dist[dist$canwr=="scnwr",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("sc")
ggplot(data=dist[dist$canwr=="fgca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("fg")
ggplot(data=dist[dist$canwr=="slnwr",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("sl")
ggplot(data=dist[dist$canwr=="tsca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("ts")
ggplot(data=dist[dist$canwr=="bkca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("bk")
ggplot(data=dist[dist$canwr=="ccnwr",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("cc")
ggplot(data=dist[dist$canwr=="dcca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("dc")
ggplot(data=dist[dist$canwr=="osca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("os")
ggplot(data=dist[dist$canwr=="tmpca",])+
  geom_point(aes(x=utm_w, y=utm_n, colour=dist))+
  ggtitle("tm")




hist(dist[dist$dist<=1500,]$dist, breaks=100)
```
